import { generateInvoiceNumber, generateInvoicePDF } from "../routes/placeOrder.js";
import crypto from "crypto";
import path from "path";
import fs from "fs";
import { fileURLToPath } from "url";
import connectDb from "../config/db.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export const getBillingPage = (req, res) => {
    res.render("billing");
};

export const generateManualInvoice = async (req, res) => {
    try {
        const { items, total } = req.body;

        const orderId = crypto.randomUUID();

        // The date is taken automatically as requested
        const invoiceData = {
            invoiceNumber: generateInvoiceNumber("INV", 8),
            date: new Date().toLocaleDateString("en-GB"),
            items,
            grandTotal: total
        };

        const invoicesDir = path.join(__dirname, "..", "..", "Invoices");
        if (!fs.existsSync(invoicesDir)) {
            fs.mkdirSync(invoicesDir, { recursive: true });
        }

        const pdfPath = path.join(invoicesDir, `invoice_${orderId}.pdf`);
        await generateInvoicePDF(invoiceData, pdfPath);

        // Cleanup the temporary QR code file generated by generateInvoicePDF
        const qrPath = path.join(__dirname, "..", "..", "Invoices", `qr_${invoiceData.invoiceNumber}.png`);
        if (fs.existsSync(qrPath)) {
            fs.unlinkSync(qrPath);
        }

        // Insert into orders table so it tracks just like a normal order
        await connectDb(
            "INSERT INTO orders (orderId, orderList, total, status) VALUES (?, ?, ?, ?)",
            [orderId, JSON.stringify(items), total, "pending"]
        );

        res.json({
            success: true,
            invoiceUrl: `/Invoices/invoice_${orderId}.pdf`
        });

    } catch (err) {
        console.error("Error generating manual invoice:", err);
        res.status(500).json({ success: false });
    }
};
