import express from "express";
const router = express.Router();

import fs from "fs";
import QRCode from "qrcode";
import pdf from "html-pdf";
import ejs from "ejs";
import path from "path";
import { fileURLToPath } from "url";
import crypto from "crypto";


import connectDb from "../config/db.js";

// ================== ES MODULE __DIRNAME ==================
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ================== INVOICE NUMBER ==================
export function generateInvoiceNumber(prefix = "INV", length = 6) {
    const random = Math.floor(Math.random() * 10 ** length)
        .toString()
        .padStart(length, "0");
    return `${prefix}-${random}`;
}

// ================== PDF GENERATION ==================
export async function generateInvoicePDF(invoiceData, outputFilePath) {
    const templatePath = path.join(
        __dirname,
        "..",
        "..",
        "frontend",
        "views",
        "invoice.ejs"
    );

    const upiId = "codewithdh@okicici";
    const upiQR = `upi://pay?pa=${upiId}&am=${invoiceData.grandTotal}&cu=INR`;

    const qrPath = path.join(
        __dirname,
        "..",
        "..",
        "Invoices",
        `qr_${invoiceData.invoiceNumber}.png`
    );

    await QRCode.toFile(qrPath, upiQR);

    const qrBase64 = fs.readFileSync(qrPath, "base64");

    const html = ejs.render(
        fs.readFileSync(templatePath, "utf8"),
        {
            data: invoiceData,
            QRCodePath: `data:image/png;base64,${qrBase64}`
        }
    );

    await new Promise((resolve, reject) => {
        pdf.create(html, { format: "A4" }).toFile(outputFilePath, err =>
            err ? reject(err) : resolve()
        );
    });
}

// ================== PLACE ORDER ==================
router.post("/", async (req, res) => {
    try {
        const { items, total } = req.body;

        const orderId = crypto.randomUUID();

        const invoiceData = {
            invoiceNumber: generateInvoiceNumber("INV", 8),
            date: new Date().toLocaleDateString("en-GB"),
            items,
            grandTotal: total
        };

        const invoicesDir = path.join(__dirname, "..", "..", "Invoices");
        fs.mkdirSync(invoicesDir, { recursive: true });

        const pdfPath = path.join(invoicesDir, `invoice_${orderId}.pdf`);
        await generateInvoicePDF(invoiceData, pdfPath);

        // Cleanup the temporary QR code file generated by generateInvoicePDF
        const qrPath = path.join(__dirname, "..", "..", "Invoices", `qr_${invoiceData.invoiceNumber}.png`);
        if (fs.existsSync(qrPath)) {
            fs.unlinkSync(qrPath);
        }

        await connectDb(
            "INSERT INTO orders (orderId, orderList, total, status) VALUES (?, ?, ?, ?)",
            [orderId, JSON.stringify(items), total, "pending"]
        );

        res.json({
            success: true,
            invoiceUrl: `/Invoices/invoice_${orderId}.pdf`
        });

    } catch (err) {
        console.error(err);
        res.status(500).json({ success: false });
    }
});

// ================== EDIT MENU ==================
router.get("/edit/meatShopMenu", async (req, res) => {
    if (!req.session || !req.session.user) {
        return res.redirect("/");
    }
    try {
        const data = await connectDb("SELECT * FROM meatShopMenu");
        res.render("editMenu", { data });
    } catch (err) {
        console.error("Error fetching menu:", err);
        res.status(500).send("Server Error");
    }
});

export default router;
